#!/usr/bin/env bash

export PATH="$CHEZMOI_WORKING_TREE/setup:$CHEZMOI_WORKING_TREE/scripts:$PATH"

# ---------------------------------- Cleanup --------------------------------- #

log info "Cleaning up..."

for app in \
  "Finder" \
  "Dock" \
  "Safari"; do
  killall "${app}" &>/dev/null
done

killall -KILL SystemUIServer
