right_format = """
$time\
"""

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

command_timeout = 3000

[character]
success_symbol = '[➜](bold blue)'

[aws]
disabled = true

[gcloud]
disabled = true

[username]
style_user = "blue bold"
show_always = true
format = "[$user]($style) "
disabled = false
#
# [hostname]
# ssh_only = false
# style = "white  bold"

[directory]
format = "[$path ]($style)"
truncate_to_repo = true

[git_branch]
symbol = ""
format = "on [$symbol $branch(:remote_branch)]($style) "

[git_status]
modified = "[!$count ](style)"
format = "[$ahead_behind$modified$untracked$stashed$conflicted$renamed$deleted]($style)"
style = "green bold"

[java]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[python]
format = '[($virtualenv )]($style)($style)'

[lua]
disabled = true

[golang]
disabled = true

[terraform]
disabled = true

[time]
disabled = false
time_format = "%R"            # Hour:Minute Format
format = "at [$time](style) "
