# format = """
# [░▒▓](#a3aed2)\
# [](bg:#769ff0 fg:#a3aed2)\
# $directory\
# [](fg:#769ff0 bg:#394260)\
# $git_branch\
# $git_status\
# $python\
# [](fg:#394260 bg:#212736)\
# $nodejs\
# $rust\
# $golang\
# """
#
right_format = """
$time\
"""

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[➜](bold blue)'

[aws]
disabled = true

[gcloud]
disabled = true

[username]
style_user = "blue bold"
show_always = true
format = "[$user]($style) "
disabled = false
#
# [hostname]
# ssh_only = false
# style = "white  bold"

[directory]
format = "in [$path ]($style)"
truncate_to_repo = true

[git_branch]
symbol = ""
format = "on [$symbol $branch(:remote_branch)]($style) "

[git_status]
modified = "[!$count ](style)"
format = '[[($all_status$ahead_behind )]($style)]($style)'
style = "green bold"


[nodejs]
disabled = true

[python]
format = '[($virtualenv )]($style)($style)'

[lua]
disabled = true

[golang]
disabled = true

[time]
disabled = false
time_format = "%R"            # Hour:Minute Format
format = "at [$time](style) "
