#!/usr/bin/env python

import subprocess
import json

EXTERNAL_MONITOR_NAMES = set(['XG248Q', 'XG248Q'])

outputs_str = subprocess.check_output('swaymsg -s $SWAYSOCK -r -t get_outputs', shell=True)
outputs = json.loads(outputs_str)

output_names = set(x["model"] for x in outputs)

if len(EXTERNAL_MONITOR_NAMES.intersection(output_names)) > 0:
    print("Dock detected")
    subprocess.check_output('swaymsg -s $SWAYSOCK output eDP-1 disable', shell=True)
else :
    print("Roaming detected")
    subprocess.check_output('swaymsg -s $SWAYSOCK output eDP-1 enable', shell=True)
