#!/usr/bin/env bash

export PATH="$CHEZMOI_WORKING_TREE/setup:$CHEZMOI_WORKING_TREE/scripts:$PATH"

log info "Installing the latest version of things that are in Atlas..."

m --stable 6.0
m --stable 7.0
m --stable 8.0

log info "Downloading the latest version of available tools..."
m tools stable
