#!/usr/bin/env bash

export PATH="$CHEZMOI_WORKING_TREE/setup:$CHEZMOI_WORKING_TREE/scripts:$PATH"

log info "Installing node-related things..."

log info "Starting with 'n'..."
curl -L https://git.io/n-install | N_PREFIX=~/.n bash -s -- -y

log info "Installing Node LTS..."
n lts

log info "Installing Node latest..."
n latest
