#!/usr/bin/env bash

export PATH="$CHEZMOI_WORKING_TREE/setup:$CHEZMOI_WORKING_TREE/scripts:$PATH"

log info "Pyenv was installed before with homebrew packages, however we need to do a couple other things to make sure everything is configured properly."

(
  cd "$HOME/GitLocal/Community" || exit 1
  curl https://pyenv.run | bash
)

export PYENV_ROOT="$HOME/GitLocal/Play/dotfiles"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

log info "Installing latest Python 3.10..."
pyenv install 3.10.16
pyenv install 3.12.9
pyenv global 3.10.16 # because there's no good way to point global to latest version

log info "Installing global python packages..."
pipx ensurepath
while IFS= read -r dep; do
  PIPX_DEFAULT_PYTHON="$(pyenv prefix)/bin/python" pipx install "$dep"
done <backup/pipx-deps.txt

log info "Installing Poetry..."
PIPX_DEFAULT_PYTHON="$(pyenv prefix)/bin/python" pipx install poetry==1.5.1
