-- Generated by nwg-displays on 2026-06-13 at 07:39:32. Do not edit manually.

hl.monitor({
	output = "DP-3",
	mode = "2560x1440@143.97",
	position = "2560x0",
	scale = 1.0,
})
hl.monitor({
	output = "HDMI-A-1",
	mode = "2560x1440@144.0",
	position = "0x0",
	scale = 1.0,
})
hl.monitor({
	output = "WAYLAND-1",
	mode = "0x0@60.0",
	position = "5120x0",
	scale = 1.0,
})
